title: "GABI pipeline report"
subtitle: "Assembly and characterization of bacterial isolates."
custom_logo: "pipelinelogo.png"
custom_logo_title: "marchoeppner/gabi"
custom_logo_url: "http://www.github.com/marchoeppner/gabi"
skip_versions_section: true

extra_fn_clean_exts:
    - _R1
    - _R2
    - _duplicate_metrics.txt
    - .pass
    - .dragonflye
    - .flye

report_comment: >
    This report has been generated automatically by marchoeppner/gabi.
    For help interpreting the outputs, please see: https://github.com/marchoeppner/gabi
report_header_info:
    - Contact E-mail: "mphoeppner@gmail.com"
    - Application Type: "Bacterial genome analysis"

top_modules:
    - 'general_stats'

report_section_order:
    software_versions:
        order: -1001
