name: autocycler_subsample
channels:
  - conda-forge
  - bioconda
  
dependencies:
  - autocycler=0.6.2
  - plassembler=1.8.2
  - raven-assembler=1.8.3
  - canu=2.3
  - miniasm=0.3
  - hifiasm=0.25.0
  - necat=0.0.1_update20200803
  - flye=2.9.6
  - minipolish>=0.2.0
  - minimap2>=2.28
  - nextdenovo>=2.5.2
  - nextpolish>=1.4.1 
  - wtdbg>=2.5  
  - racon>=1.5.0 
  - metamdbg>=1.0 
  - myloasm>=0.1.0
